[package]
name = "ksi-math-rs"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Basic math lib for Rust."
keywords = ["math"]
repository = "https://github.com/Kseen715/ksi-math-rs.git"
readme = "README.md"

[dependencies]

[[bin]]
name = "test"
path = "src/ksi_math.rs"
